# -*- coding: utf-8 -*-
"""Calculadora em python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qoxHeJMOzq26ay8hnPNn_agIoUtIhhRr

Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual número ele deseja ver a tabuada.

Lembre-se de que você já conhece o nível intermediário da linguagem de programação Python, além de conhecer como automatizar dados por meio da programação funcional e programação orientada a objetos.

Após resolver o desafio, preencha o checklist a seguir.
"""

def tabuada(valor: int):
  print(f'TABUADA DO {valor}\n')
  for i in range(0,11):
    print(f'{valor} x {i} = {valor*i}')

import time

escolha = 'S'

while(escolha.upper()!='N'):

  if(escolha.upper()=='S'):
    valor = int(input('Digite o número desejado para exibir a tabuada: '))
    tabuada(valor)
    time.sleep(1)
    print('\nVocê quer ver uma nova lista da tabuada?')
    escolha = str(input('Digite S para continuar e N para encerrar: '))

    while(escolha.upper()!='N' and escolha.upper()!='S'):
      print('O valor que você digitou é inválido, digite novamente: ')
      escolha = input()