# -*- coding: utf-8 -*-
"""Análise das empresas unicórnio 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HYwtdhIj57iISdfsDT7Vm5tBiD6mAbEi

# Imports

"Unicórnio" é um termo usado na indústria de capital de risco para descrever uma startup de capital fechado com valor superior a US$ 1 bilhão. O termo foi popularizado pela primeira vez pela capitalista de risco Aileen Lee, fundadora da Cowboy Ventures, um fundo de capital de risco com sede em Palo Alto, Califórnia.

Sabendo do seu significado e importância, verificou-se a necessidade de analisar como as industrias brasileiras se encontravam no ano de 2022 o link para download do arquivo foi retirado do kaggle: https://www.kaggle.com/datasets/ramjasmaurya/unicorn-startups
"""

import numpy as np
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt

"""# Leitura dos dados"""

dados = pd.read_csv('unicorns till sep 2022.csv')

dados.shape

dados.head()

dados.columns

dados.rename(columns={
    'Company':'Companhia',
    'Valuation ($B)': 'Avaliação ($B)',
    'Date Joined': 'Data de Adesão',
    'Country': 'País',
    'City\xa0': 'Cidade',
    'Industry': 'Industria',
    'Investors':'Investidores'
},
             inplace = True)

"""#Verificação"""

dados.info()

dados.isnull().sum()

"""#Conversão do tipo"""

dados['Data de Adesão'] = pd.to_datetime(dados['Data de Adesão'])

"""##Removendo o $ e convertendo para o tipo float"""

dados['Avaliação ($B)'] = dados['Avaliação ($B)'].str.replace('$','')
dados['Avaliação ($B)'] = pd.to_numeric(dados['Avaliação ($B)'])

"""#Análise"""

dados['Industria'].value_counts()

"""### Gráfico de barra"""

#configuração do gráfico de barra
plt.figure(figsize = (11,5))
plt.grid(which='both', alpha=0.3)
plt.title('Rank de industrias mais presentes globalmente')

#configuração da legenda das barras
plt.xticks(rotation = 45, ha='right')

#gráfico de barra
plt.bar(
    dados['Industria'].value_counts().head(10).index,
    dados['Industria'].value_counts().head(10),
    color='orange'
    );

"""###Insight

A indústria que possui maior presença como empresa unicórnio é a Fintech e Internet software & services, mostrando a expansão crescente dessas áreas

##Análise do Brasil
"""

dados_brasil = dados.loc[dados['País'] == 'Brazil'].reset_index()

dados_brasil

#configuração do gráfico de barra
plt.figure(figsize = (9,5))
plt.grid(which='both', alpha=0.3)
plt.title('Rank de industrias mais presentes no Brasil')

#configuração da legenda das barras
plt.xticks(rotation = 45, ha='right')

#gráfico de barra
plt.bar(
    dados_brasil['Industria'].value_counts().head(10).index,
    dados_brasil['Industria'].value_counts().head(10),
    color='orange'
    );

"""###Insight
Comparando o gráfico com o anterior que mostra de forma global com este do Brasil, notou-se algumas diferenças como no terceiro lugar entrar logistica, delivery e cadeia de mantimentos, mas em primeiro e segundo lugar continuam nas mesmas posições indicando como essa área é bem presente não só globalmente mas como no Brasil, chegando a ter 6 industrias "Fintech" e "E-commerce"
"""

analise_brasil = round(dados_brasil['Cidade'].value_counts(normalize=True) *100,1)

plt.figure(figsize=(15,5))
plt.title('Cidade com maior fluxo de empresas unicórnio')

plt.pie(
    analise_brasil,
    labels=analise_brasil.index,
    startangle=90,
    autopct = '%1.1f%%'
);

"""###Insight
A cidade de São Paulo é o que constitui 70% das empresas unicórnio no Brasil onde a segunda maior porcentagem é Curitiba
"""

dados_brasil[[
    'Companhia',
    'Cidade',
    'Data de Adesão',
    'Avaliação ($B)']].sort_values('Avaliação ($B)', ascending=False)

"""### Insight
As empresas que possuem uma avaliação acima de 4 bilhões são Quinto Andar e C6Bank localizado na cidade de Campinas e São Paulo respectivamente
"""